version: "3"
services:
  postgres:
    image: postgres:12-alpine
    container_name: "postgres"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sensor_data
    volumes:
      - ./src/test/resources/init-db.sql:/docker-entrypoint-initdb.d/init.sql
